FROM node:alpine AS build
WORKDIR /app
RUN npm install -g pnpm
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY pnpm-lock.yaml ./
RUN pnpm i --production
RUN pnpm i react-scripts@3.4.1
COPY . ./
RUN pnpm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]