version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DATABASE=messenger
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3002:3002"
    logging:
      driver: none
    volumes: 
      - db:/var/lib/postgresql/data
  server:
    build: server/
    restart: always
    environment:
      - EXTERNAL_PORT=3001
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=messenger
      - POSTGRES_HOST=host.docker.internal
    ports:
      - "3001:3001"
    command: pnpm dev
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./server:/src
      - /server/src/node_modules/
  client:
    build: client/
    restart: always
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    command: pnpm start
    depends_on:
      - server
    volumes:
      - ./client:/src
      - /client/src/node_modules/
volumes:
  db:
    driver: local