version: '3'
services:
  server:
    build: server/
    restart: always
    environment:
      - EXTERNAL_PORT=80
      - POSTGRES_USER_DEV=${POSTGRES_USER_DEV}
      - POSTGRES_PASSWORD_DEV=${POSTGRES_PASSWORD_DEV}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST_DEV=${POSTGRES_HOST_DEV}
      - POSTGRES_PORT_DEV=${POSTGRES_PORT_DEV}
      - NODE_ENV=development
      - SESSION_SECRET=${SESSION_SECRET}
    ports:
      - '80:80'
    command: pnpm dev
    volumes:
      - ./server:/app
      - /server/app/node_modules/
  client:
    build: client/
    restart: always
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - '3000:3000'
    command: pnpm start
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /client/app/node_modules/
