version: "3"
services:
  api:
    image: ${DOCKER_REGISTRY}/backend
    build: 
      dockerfile: Dockerfile.prod
      context: ./server
    environment:
      - POSTGRES_USER_PROD=${POSTGRES_USER_PROD}
      - POSTGRES_PASSWORD_PROD=${POSTGRES_PASSWORD_PROD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST_PROD=${POSTGRES_HOST_PROD}
      - POSTGRES_PORT_PROD=${POSTGRES_PORT_PROD}
      - NODE_ENV=production
      - SESSION_SECRET=${SESSION_SECRET}
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /server/app/node_modules/
  client:
    image: ${DOCKER_REGISTRY}/frontend
    build: 
      dockerfile: Dockerfile.prod
      context: ./client
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "4200:8080"
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /client/app/node_modules/
